site_name: CoreProtect Time-Lapse Docs
theme: readthedocs
repo_url: https://github.com/R2bEEaton-Minecraft/CoreProtectTimeLapse
extra_css:
  - css/css.css
nav:
  - Welcome to CPTL Docs: index.md
  - Commands: commands.md
  - Compatibility: compatibility.md
  - Full Usage Guide: usage.md
  - Donate: donate.md
